'''
You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a
random position. Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
'''


def findTheDifference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    if len(s) == 0:
        return t
    for char in t:
        if char not in s:
            return char
        elif s.count(char) != t.count(char):        # This else is for cases when for example s = "a" and t = "aa"
            return char


print(findTheDifference("abcd", "abcde"))